
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class jfrmCalcbasic extends java.awt.Frame {
   LocalDate fechaActual = LocalDate.now();
   DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE, MMM, YYYY");
   String chejo = fechaActual.format(formato);
   
   int valor1, valor2;
    public jfrmCalcbasic() {
        initComponents();
        jtxtFecha.setText(chejo);
        this.setLocation(800,300);
        this.setExtendedState(jfrmCalcbasic.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtFecha = new javax.swing.JTextField();
        jtxtNum1 = new javax.swing.JTextField();
        jtxtNum2 = new javax.swing.JTextField();
        jbtnmas1 = new javax.swing.JButton();
        jbtnmas2 = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        jbtnSUMA = new javax.swing.JButton();
        RESTA = new javax.swing.JButton();
        DIVISION = new javax.swing.JButton();
        MULTIPLICAR = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Calculadora basica:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Digite otro valor numerico");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel4.setText("Escriba un valor numerico");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jtxtFecha.setEnabled(false);
        jtxtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 250, -1));

        jtxtNum1.setText("0");
        jtxtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNum1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, 30));

        jtxtNum2.setText("0");
        jPanel1.add(jtxtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 220, 30));

        jbtnmas1.setText("+1");
        jbtnmas1.setToolTipText("");
        jbtnmas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmas1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnmas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jbtnmas2.setText("+1");
        jbtnmas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmas2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnmas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        labelResultado.setText("Resultado:");
        labelResultado.setToolTipText("");
        jPanel1.add(labelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jbtnSUMA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnSUMA.setText("+");
        jbtnSUMA.setToolTipText("");
        jbtnSUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSUMAActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSUMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, 40));

        RESTA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RESTA.setText("-");
        RESTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTAActionPerformed(evt);
            }
        });
        jPanel1.add(RESTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 70, 40));

        DIVISION.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DIVISION.setText("/");
        DIVISION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVISIONActionPerformed(evt);
            }
        });
        jPanel1.add(DIVISION, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 70, 40));

        MULTIPLICAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MULTIPLICAR.setText("x");
        MULTIPLICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTIPLICARActionPerformed(evt);
            }
        });
        jPanel1.add(MULTIPLICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 70, 40));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jbtnmas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmas1ActionPerformed
        valor1=Integer.parseInt(jtxtNum1.getText());
        //Contador
        valor1=valor1+1;
        jtxtNum1.setText(String.valueOf(valor1));
    }//GEN-LAST:event_jbtnmas1ActionPerformed

    private void jtxtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFechaActionPerformed

    private void jtxtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNum1ActionPerformed

    private void RESTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTAActionPerformed
        int num1, num2;
        num1=Integer.parseInt(jtxtNum1.getText());
        num2=Integer.parseInt(jtxtNum2.getText());
        int resta=num1-num2;
        labelResultado.setText(String.valueOf("Resultado: " + resta));
    }//GEN-LAST:event_RESTAActionPerformed

    private void MULTIPLICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTIPLICARActionPerformed
        int num1, num2;
        num1=Integer.parseInt(jtxtNum1.getText());
        num2=Integer.parseInt(jtxtNum2.getText());
        int multiplicación=num1*num2;
        labelResultado.setText(String.valueOf("Resultado: " + multiplicación));
    }//GEN-LAST:event_MULTIPLICARActionPerformed

    private void jbtnSUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSUMAActionPerformed
        int num1, num2;
        num1=Integer.parseInt(jtxtNum1.getText());
        num2=Integer.parseInt(jtxtNum2.getText());
        int suma=num1+num2;
        labelResultado.setText(String.valueOf("Resultado: " + suma));
    }//GEN-LAST:event_jbtnSUMAActionPerformed

    private void DIVISIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVISIONActionPerformed
        int num1, num2;
        num1=Integer.parseInt(jtxtNum1.getText());
        num2=Integer.parseInt(jtxtNum2.getText());
        int dividir=num1/num2;
        labelResultado.setText(String.valueOf("Resultado: " + dividir));
    }//GEN-LAST:event_DIVISIONActionPerformed

    private void jbtnmas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmas2ActionPerformed
        valor2=Integer.parseInt(jtxtNum2.getText());
        //Contador
        valor2=valor2+1;
        jtxtNum1.setText(String.valueOf(valor2));
    }//GEN-LAST:event_jbtnmas2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalcbasic().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DIVISION;
    private javax.swing.JButton MULTIPLICAR;
    private javax.swing.JButton RESTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSUMA;
    private javax.swing.JButton jbtnmas1;
    private javax.swing.JButton jbtnmas2;
    private javax.swing.JTextField jtxtFecha;
    private javax.swing.JTextField jtxtNum1;
    private javax.swing.JTextField jtxtNum2;
    private javax.swing.JLabel labelResultado;
    // End of variables declaration//GEN-END:variables
}
